version: '3.9'

services:
  defi_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: defi_web
    restart: on-failure
    environment:
      - PORT=${PORT}
    expose:
      - ${PORT}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/
      - ./public:/app/
      - ./internals:/app/
      - ./.env:/app/.env
    env_file: ./.env
    command: yarn start
